### ISSUE TITLE
Kube Resource View - Allow inline mapping of instance costs

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#434]
e.g.:

```yaml
kubeResourceView:
       costs: 
          "vsphere-vm.cpu-2.mem-8gb.os-linux": 200
```
