### ISSUE TITLE
Deploy MongoDB operator

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#658]
https://github.com/percona/percona-server-mongodb-operator + karina template:

```yaml
apiVersion: db.flanksource.com/v1
kind: MongoDB
metadata:
  name: datastore
spec:
  backup:
    bucket: mongo-backups
    schedule: "0 */4 * * *"
  cpu: 4000m
  memory: 8Gi
  replicas: 3
  storage:
    size: 200Gi
    storageClass: io2
  parameters: {}
```
