### ISSUE TITLE
Redis template

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#671]
```yaml
apiVersion: db.flanksource.com/v1
kind: Redis
metadata:
  name: redis-db1
spec:
  backup:
    bucket: postgres-backups
    schedule: "0 */4 * * *"
  cpu: 4000m
  memory: 8Gi
  replicas: 3
  storage:
    size: 200Gi
  parameters: {}

```
