### ISSUE TITLE
Replace elasticsearch config with template

### ISSUE THREAD

**Issue by moshloop** [flanksource/karina#706]
i.e. remove https://karina.docs.flanksource.com/reference/config/#elasticsearch and replace with:

```yaml
apiVersion: db.flanksource.com/v1
kind: Elasticsearch
spec:
  version:
  memory:
  cpu: 
  replicas:
```
