### ISSUE TITLE
Using custom image for kind-cluster provisioning doesn't work

### ISSUE THREAD

**Issue by tobernguyen** [flanksource/karina#793]
My `karina.yml`
```
domain: 127.0.0.1.nip.io
name: test-cluster
kind:
  workerCount: 3
  image: rossgeorgiev/kind-node-arm64:v1.18.17
localPath:
  disabled: false
calico:
  version: v3.8.2
kubernetes:
  version: v1.18.6
  masterIP: localhost
  containerRuntime: containerd
ca:
  cert: .certs/root-ca.crt
  privateKey: .certs/root-ca.key
  password: foobar
ingressCA:
  cert: .certs/ingress-ca.crt
  privateKey: .certs/ingress-ca.key
  password: foobar
```
- Then I ran `karina pvorision kind-cluster`, it doesn't create kind cluster with the image I specified. Instead, it uses `kindest/node:v1.18.6`
```
➜ karina provision kind-cluster
Creating cluster "test-cluster" ...
 • Ensuring node image (kindest/node:v1.18.6) 🖼  ...
 ✓ Ensuring node image (kindest/node:v1.18.6) 🖼
 • Preparing nodes 📦  ...
```
